<?php
require('system/config.php');
 
/**
 * Check if the user is logged in.
 */
if(!isset($_SESSION['user_id']) || !isset($_SESSION['logged_in'])){
    //User not logged in. Redirect them back to the login.php page.
    header('Location: login.php');
    exit;
}

if(!isset($_SESSION['user_type']) || $_SESSION['user_type'] != 2){
	// User isn't an administrator, redirect back to home page.
	header('Location: index.php');
	exit;
}

if(isset($_POST['add-user']) && $_POST['add-user'] == 1){
	
	global $pdo;
	
	$errors = array();
	
	$name = $_POST['name'];
	$email = $_POST['email_address'];
	$user_type = $_POST['user_type'];
	
	$username = generate_username($name);
	$password = randomPassword();
	$hashedPassword = hashPassword($password);
	
	if(!checkEmailExists($email)){
		$sql = "INSERT INTO users (username, name, email_address, password, user_type) VALUES(?,?,?,?,?)";
		
		$stmt = $pdo->prepare($sql);
		
		$stmt->execute([$username, $name, $email, $hashedPassword, $user_type]);
		
		$newUserId = $pdo->lastInsertId();
		
		if(!sendUserNewPassword($newUserId,$password)){
			$errors["error_sending"] = "Error sending email to user";
		}
	}else{
		$errors["email_exists"] = "Email already exists!";
	}
	
	if(count($errors) == 0){
		header('Location: admin-edit-user.php?id='.$newUserId);
	}
		
}
$page = "admin-users";
$page_title = 'Reloc8UK Admin - Add New User';
$portal_extra_head = '<link rel="stylesheet" type="text/css" href="assets/css/admin-crm-forms.css?ver='.time().'">';
include_once("views/header.php");
?>
		<div class="admin-crm-page">
		<div class="card admin-crm-page-header mb-4">
			<div class="card-body">
				<div class="admin-crm-page-header__row">
					<div>
						<h1 class="admin-crm-page-header__title">Add New User</h1>
						<p class="admin-crm-page-header__subtitle">Add a new user to the property portal.</p>
					</div>
				</div>
			</div>
		</div>
		<div class="card admin-crm-panel mb-4">
			<div class="card-header">
				<span class="iconify" data-icon="mdi:account-plus-outline"></span>
				<h5>User details</h5>
			</div>
			<div class="card-body">
			<form method="post" action="<?php echo $_SERVER['PHP_SELF']; ?>">
				<input type="hidden" name="add-user" value="1">
				<div class="admin-crm-section">
					<h6 class="admin-crm-section__title"><span class="iconify" data-icon="mdi:account-outline"></span>Account information</h6>
					<div class="row g-3">
						<div class="col-md-4 col-sm-12">
							<label for="name" class="admin-crm-label">Full Name</label>
							<input type="text" name="name" id="name" class="form-control admin-crm-control" placeholder="User's full name" />
						</div>
						<div class="col-md-4 col-sm-12">
							<label for="email_address" class="admin-crm-label">Email Address</label>
							<input type="email" name="email_address" id="email_address" class="form-control admin-crm-control" placeholder="User's email address" />
						</div>
						<div class="col-md-4 col-sm-12">
							<label for="user_type" class="admin-crm-label">User Type</label>
							<select name="user_type" id="user_type" class="form-select admin-crm-control" required>
								<option value="1">Council</option>
								<option value="4">Council (limited)</option>
								<option value="2">Administrator</option>
								<option value="3">Tenant</option>
							</select>
						</div>
					</div>
				</div>
				<div class="admin-crm-section">
					<h6 class="admin-crm-section__title"><span class="iconify" data-icon="mdi:information-outline"></span>Important notes</h6>
					<div class="admin-crm-subpanel">
						<p class="admin-crm-field-hint mb-2">Tenants must register on the front end of the portal to capture all of their data.</p>
						<p class="admin-crm-field-hint mb-2">Usernames and passwords will automatically be generated by the system and sent to the user.</p>
						<p class="admin-crm-field-hint mb-0">Users with user type <em>Administrator</em> will have <strong>full permission access</strong> to the portal, allowing them to add/edit/delete properties &amp; users.</p>
					</div>
				</div>
				<div class="admin-crm-submit-wrap admin-crm-submit-wrap--end">
					<button type="submit" class="btn btn-crm-primary btn-lg"><span class="iconify" data-icon="mdi:account-plus-outline"></span>Add User</button>
				</div>
			</form>
			</div>
		</div>
		</div>
<?php include_once("views/footer.php"); ?>
<script type="text/javascript">
$(document).ready(function(){
	function randString(id){
	var dataSet = $(id).attr('data-character-set').split(',');  
	var possible = '';
	if($.inArray('a-z', dataSet) >= 0){
		possible += 'abcdefghijklmnopqrstuvwxyz';
	}
	if($.inArray('A-Z', dataSet) >= 0){
		possible += 'ABCDEFGHIJKLMNOPQRSTUVWXYZ';
	}
	if($.inArray('0-9', dataSet) >= 0){
		possible += '0123456789';
	}
	if($.inArray('#', dataSet) >= 0){
		possible += '![]{}()%&*$#^<>~@|';
	}
	var text = '';
		for(var i=0; i < $(id).attr('data-size'); i++) {
			text += possible.charAt(Math.floor(Math.random() * possible.length));
		}
		return text;
	}
	$('input[rel="gp"]').each(function(){
		$(this).val(randString($(this)));
	});
});
</script>