<?php
require('system/config.php');
 
/**
 * Check if the user is logged in.
 */
if(!isset($_SESSION['user_id']) || !isset($_SESSION['logged_in'])){
    //User not logged in. Redirect them back to the login.php page.
    header('Location: login.php');
    exit;
}

if(!isset($_SESSION['user_type']) || $_SESSION['user_type'] != 2){
	// User isn't an administrator, redirect back to home page.
	header('Location: index.php');
	exit;
}

if(isset($_POST['add-user']) && $_POST['add-user'] == 1){
	
	global $pdo;
	
	$errors = array();
	
	$name = $_POST['name'];
	$email = $_POST['email_address'];
	$user_type = $_POST['user_type'];
	
	$username = generate_username($name);
	$password = randomPassword();
	$hashedPassword = hashPassword($password);
	
	if(!checkEmailExists($email)){
		$sql = "INSERT INTO users (username, name, email_address, password, user_type) VALUES(?,?,?,?,?)";
		
		$stmt = $pdo->prepare($sql);
		
		$stmt->execute([$username, $name, $email, $hashedPassword, $user_type]);
		
		if(!sendUserNewPassword($pdo->lastInsertId(),$password)){
			$errors["error_sending"] = "Error sending email to user";
		}
	}else{
		$errors["email_exists"] = "Email already exists!";
	}
	
	if(count($errors) == 0){
		header('Location: admin.php');
	}
		
}
$page = "admin";
?>
<!DOCTYPE html>
<head>
<title>Reloc8UK Admin - Add New User</title>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<style type="text/css">
#primary-nav {
  background-color: #545659;
  color: white;
}
#primary-nav a {
	color: white;
}

</style>
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.20/css/jquery.dataTables.min.css">
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/responsive/2.2.3/css/responsive.dataTables.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/open-iconic/1.1.1/font/css/open-iconic-bootstrap.min.css" integrity="sha256-BJ/G+e+y7bQdrYkS2RBTyNfBHpA9IuGaPmf9htub5MQ=" crossorigin="anonymous" />
<link rel="stylesheet" type="text/css" href="assets/css/styles.css?ver=<?php echo time(); ?>">
<script src="https://code.jquery.com/jquery-3.4.1.min.js" ></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
<script type="text/javascript" src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"></script>
<script type="text/javascript" src="//cdn.datatables.net/responsive/2.2.3/js/dataTables.responsive.js"></script>
</head>
<body class="bg-light">
<?php
include_once("views/navbar.php");
?>
<main role="main" class="container">
	<div class="my-3 p-3 bg-white rounded shadow-sm">
		<h4 class="border-bottom border-gray pb-2 mb-0">Add New User</h4>
		<p class="lead">Add a new user to the property portal.</p>
	</div>
	<div class="my-3 p-3 bg-white rounded shadow-sm">
		<form method="post" action="<?php echo $_SERVER['PHP_SELF']; ?>">
			<input type="hidden" name="add-user" value="1">
			<div class="p-2 bg-light mb-2">
				<div class="form-group row my-2">
					<div class="col-md-4 col-sm-12">
						<label for="name">Full Name</label>
						<input type="text" name="name" class="form-control" placeholder="User's full name" />
					</div>
					<div class="col-md-4 col-sm-12">
						<label for="email_address">Email Address</label>
						<input type="email" name="email_address" class="form-control" placeholder="User's email address" />
					</div>
					<div class="col-md-4 col-sm-12">
						<label for="user_type">User Type</label>
						<select name="user_type" class="form-control" required>
							<option value="1">Council</option>
							<option value="4">Council (limited)</option>
							<option value="2">Administrator</option>
							<option value="3">Tenant</option>
						</select>
					</div>
				</div>	
			</div>
			<div class="p-2 bg-light mb-2">
				<div class="form-group row my-2">
					<div class="col-md-12">
						<p class="lead">NOTE: Tenants must register on the front end of the portal to capture all of their data.</p>
						<p class="lead">Usernames and passwords will automatically be generated by the system and sent to the user.</p>
						<p class="lead">Users with user type <i>Administrator</i> will have <b>full permission access</b> to the portal, allowing them to add/edit/delete properties & users.</p>
					</div>
				</div>
				<div class="form-group row my-2">
					<div class="col-md-12 text-center justify-content-center">
						<button class="btn btn-secondary btn-lg">Add User</button>
					</div>
				</div>
			</div>
		</form>
	</div>
</main>
<footer>
		<div class="copyright text-center py-2">
			<small>&copy; Copyright <?php echo date("Y"); ?> Midland Relocations Limited.</small>
		</div>
	</footer>
<script type="text/javascript">
$(document).ready(function(){
	function randString(id){
	var dataSet = $(id).attr('data-character-set').split(',');  
	var possible = '';
	if($.inArray('a-z', dataSet) >= 0){
		possible += 'abcdefghijklmnopqrstuvwxyz';
	}
	if($.inArray('A-Z', dataSet) >= 0){
		possible += 'ABCDEFGHIJKLMNOPQRSTUVWXYZ';
	}
	if($.inArray('0-9', dataSet) >= 0){
		possible += '0123456789';
	}
	if($.inArray('#', dataSet) >= 0){
		possible += '![]{}()%&*$#^<>~@|';
	}
	var text = '';
		for(var i=0; i < $(id).attr('data-size'); i++) {
			text += possible.charAt(Math.floor(Math.random() * possible.length));
		}
		return text;
	}
	$('input[rel="gp"]').each(function(){
		$(this).val(randString($(this)));
	});
});
</script>
</body>
</html>